/** Interaction history demo data - separated from dummyData for reliable module loading. */
import { DUMMY_CAMPAIGNS, DUMMY_VOICE_TRANSCRIPTS } from './dummyData.js';

/** Completed customer interactions across all outreach channels. */
export const DUMMY_INTERACTION_HISTORY = [
  {
    interaction_id: 'int-001',
    customer_name: 'Priya Nair',
    customer_id: 'demo-lead-001',
    phone: '9876543210',
    date: '2026-07-14T10:23:00.000Z',
    channel: 'Voice',
    campaign: 'Q3 Personal Loan Drive',
    campaign_id: 'cmp-001',
    duration: '2m 14s',
    duration_seconds: 134,
    outcome: 'Interested',
    sentiment: 'Positive',
    status: 'completed',
    agent: 'TARA Voice AI',
    intent: 'Loan documentation inquiry',
    summary: 'Customer interested in Personal Loan. WhatsApp application link sent.',
    reasoning: 'High conversion intent — customer asked about documentation. ML score 78% confirmed.',
    transcript: DUMMY_VOICE_TRANSCRIPTS['demo-lead-001']?.map(({ sender, text }) => ({ sender, text })) || [],
  },
  {
    interaction_id: 'int-002',
    customer_name: 'Rahul Sharma',
    customer_id: 'demo-lead-002',
    phone: '9123456780',
    date: '2026-07-13T15:45:00.000Z',
    channel: 'Voice',
    campaign: 'Gold Credit Card Upgrade',
    campaign_id: 'cmp-002',
    duration: '1m 52s',
    duration_seconds: 112,
    outcome: 'Follow-up Scheduled',
    sentiment: 'Neutral-Positive',
    status: 'completed',
    agent: 'TARA Voice AI',
    intent: 'Credit limit inquiry',
    summary: 'Gold Credit Card benefits emailed. Customer will decide over the weekend.',
    reasoning: 'Initial objection handled. Customer requested email — nurture track activated.',
    transcript: DUMMY_VOICE_TRANSCRIPTS['demo-lead-002']?.map(({ sender, text }) => ({ sender, text })) || [],
  },
  {
    interaction_id: 'int-003',
    customer_name: 'Ananya Iyer',
    customer_id: 'demo-lead-003',
    phone: '9988776655',
    date: '2026-07-12T09:10:00.000Z',
    channel: 'Email',
    campaign: 'Gold Credit Card Upgrade',
    campaign_id: 'cmp-002',
    duration: '—',
    duration_seconds: 0,
    outcome: 'Opened',
    sentiment: 'Neutral',
    status: 'completed',
    agent: 'TARA Email Agent',
    intent: 'Product awareness',
    summary: 'Personalised credit card upgrade email delivered and opened within 2 hours.',
    reasoning: 'Email engagement signal recorded. Lead remains in nurture sequence.',
    transcript: [],
  },
  {
    interaction_id: 'int-004',
    customer_name: 'Arjun Das',
    customer_id: 'lead-6',
    phone: '9876543210',
    date: '2026-06-28T11:30:00.000Z',
    channel: 'WhatsApp',
    campaign: 'Digital Savings Promotion',
    campaign_id: 'cmp-003',
    duration: '4m 05s',
    duration_seconds: 245,
    outcome: 'Converted',
    sentiment: 'Positive',
    status: 'completed',
    agent: 'TARA WhatsApp Agent',
    intent: 'Account opening',
    summary: 'Digital Savings Account opened via WhatsApp-guided flow.',
    reasoning: 'Customer completed KYC steps in-chat. Conversion logged to CRM.',
    transcript: [
      { sender: 'agent', text: 'Hi Arjun! Your Digital Savings Account offer is ready. Shall I walk you through opening?' },
      { sender: 'user', text: 'Yes please, I have my documents ready.' },
      { sender: 'agent', text: 'Great — tap the link below to start video KYC. It takes about 8 minutes.' },
      { sender: 'user', text: 'Done! Account is active.' },
      { sender: 'agent', text: 'Congratulations! Your virtual debit card is now available in YONO.' },
    ],
  },
  {
    interaction_id: 'int-005',
    customer_name: 'Vikram Patel',
    customer_id: 'lead-2',
    phone: '9012345678',
    date: '2026-07-11T16:20:00.000Z',
    channel: 'SMS',
    campaign: 'Q3 Personal Loan Drive',
    campaign_id: 'cmp-001',
    duration: '—',
    duration_seconds: 0,
    outcome: 'Link Clicked',
    sentiment: 'Neutral',
    status: 'completed',
    agent: 'TARA SMS Agent',
    intent: 'Offer exploration',
    summary: 'Pre-approved loan SMS sent. Customer clicked application link.',
    reasoning: 'Click-through within 45 minutes indicates warm intent.',
    transcript: [],
  },
  {
    interaction_id: 'int-006',
    customer_name: 'Meera Krishnan',
    customer_id: 'demo-lead-005',
    phone: '9765432109',
    date: '2026-07-10T14:05:00.000Z',
    channel: 'Voice',
    campaign: 'Q3 Personal Loan Drive',
    campaign_id: 'cmp-001',
    duration: '1m 56s',
    duration_seconds: 116,
    outcome: 'Converted',
    sentiment: 'Positive',
    status: 'completed',
    agent: 'TARA Voice AI',
    intent: 'Recurring deposit setup',
    summary: 'Recurring Deposit mandate initiated at ₹2,000/month for 24 months.',
    reasoning: 'Customer accepted RD offer with modified amount. Auto-debit mandate created.',
    transcript: DUMMY_VOICE_TRANSCRIPTS['demo-lead-005']?.map(({ sender, text }) => ({ sender, text })) || [],
  },
  {
    interaction_id: 'int-007',
    customer_name: 'Sana Khan',
    customer_id: 'lead-7',
    phone: '8899001122',
    date: '2026-06-25T08:55:00.000Z',
    channel: 'WhatsApp',
    campaign: 'Digital Savings Promotion',
    campaign_id: 'cmp-003',
    duration: '3m 22s',
    duration_seconds: 202,
    outcome: 'Converted',
    sentiment: 'Positive',
    status: 'completed',
    agent: 'TARA WhatsApp Agent',
    intent: 'Savings upgrade',
    summary: 'Premium Savings Plus upgrade completed via WhatsApp.',
    reasoning: 'Long-tenure customer. Self-service path completed successfully.',
    transcript: [
      { sender: 'agent', text: 'Hello Sana! You qualify for Premium Savings Plus at 7.1% interest.' },
      { sender: 'user', text: 'Sounds good. How do I upgrade?' },
      { sender: 'agent', text: 'I have sent a secure upgrade link. Tap to confirm in YONO.' },
      { sender: 'user', text: 'Upgraded successfully. Thank you!' },
    ],
  },
  {
    interaction_id: 'int-008',
    customer_name: 'Rohan Gupta',
    customer_id: 'lead-8',
    phone: '9012345678',
    date: '2026-06-20T17:40:00.000Z',
    channel: 'Email',
    campaign: 'Digital Savings Promotion',
    campaign_id: 'cmp-003',
    duration: '—',
    duration_seconds: 0,
    outcome: 'No Response',
    sentiment: 'Neutral',
    status: 'completed',
    agent: 'TARA Email Agent',
    intent: 'Product awareness',
    summary: 'Savings promotion email delivered. No open or click recorded after 7 days.',
    reasoning: 'Low engagement score. Lead flagged for re-segmentation.',
    transcript: [],
  },
  {
    interaction_id: 'int-009',
    customer_name: 'Vikram Patel',
    customer_id: 'demo-lead-004',
    phone: '9123456789',
    date: '2026-07-09T12:15:00.000Z',
    channel: 'Voice',
    campaign: 'Digital Savings Promotion',
    campaign_id: 'cmp-003',
    duration: '1m 22s',
    duration_seconds: 82,
    outcome: 'Callback Scheduled',
    sentiment: 'Neutral',
    status: 'completed',
    agent: 'TARA Voice AI',
    intent: 'Digital account opening',
    summary: 'Digital account opening deferred. WhatsApp callback link sent for video KYC.',
    reasoning: 'Timing objection — callback scheduled. Lead remains warm.',
    transcript: DUMMY_VOICE_TRANSCRIPTS['demo-lead-004']?.map(({ sender, text }) => ({ sender, text })) || [],
  },
  {
    interaction_id: 'int-010',
    customer_name: 'Ananya Iyer',
    customer_id: 'demo-lead-003',
    phone: '9988776655',
    date: '2026-07-08T10:00:00.000Z',
    channel: 'Voice',
    campaign: 'Gold Credit Card Upgrade',
    campaign_id: 'cmp-002',
    duration: '1m 48s',
    duration_seconds: 108,
    outcome: 'Interested',
    sentiment: 'Positive',
    status: 'completed',
    agent: 'TARA Voice AI',
    intent: 'Savings upgrade',
    summary: 'Premium Savings Plus upgrade discussed. Customer will self-serve via YONO app.',
    reasoning: 'Long-tenure customer with high loyalty score. SMS upgrade link sent.',
    transcript: DUMMY_VOICE_TRANSCRIPTS['demo-lead-003']?.map(({ sender, text }) => ({ sender, text })) || [],
  },
  {
    interaction_id: 'int-011',
    customer_name: 'Deepak Menon',
    customer_id: 'ext-4412',
    phone: '9445566778',
    date: '2026-07-07T13:30:00.000Z',
    channel: 'Multi-Channel',
    campaign: 'Q3 Personal Loan Drive',
    campaign_id: 'cmp-001',
    duration: '6m 10s',
    duration_seconds: 370,
    outcome: 'Interested',
    sentiment: 'Positive',
    status: 'completed',
    agent: 'TARA Orchestrator',
    intent: 'Loan eligibility',
    summary: 'Multi-channel sequence: email opened → SMS link clicked → voice follow-up completed.',
    reasoning: 'Cross-channel engagement indicates high intent. Handoff to loan specialist queued.',
    transcript: [
      { sender: 'agent', text: 'Following up on your Personal Loan interest from our earlier messages.' },
      { sender: 'user', text: 'Yes, I reviewed the email. What rate can I get?' },
      { sender: 'agent', text: 'Based on your profile, you qualify for 10.9% with up to ₹8.5 lakhs.' },
      { sender: 'user', text: 'Please send the application link again.' },
      { sender: 'agent', text: 'Link resent via WhatsApp and SMS. A specialist will call tomorrow.' },
    ],
  },
  {
    interaction_id: 'int-012',
    customer_name: 'Kavitha Reddy',
    customer_id: 'ext-2298',
    phone: '9556677889',
    date: '2026-07-06T09:45:00.000Z',
    channel: 'Voice',
    campaign: 'Q3 Personal Loan Drive',
    campaign_id: 'cmp-001',
    duration: '0m 38s',
    duration_seconds: 38,
    outcome: 'No Answer',
    sentiment: 'Neutral',
    status: 'completed',
    agent: 'TARA Voice AI',
    intent: '—',
    summary: 'Outbound call — no answer after 4 rings. Voicemail not left per policy.',
    reasoning: 'Retry scheduled for next business day morning slot.',
    transcript: [],
  },
  {
    interaction_id: 'int-013',
    customer_name: 'Rohan Gupta',
    customer_id: 'lead-8',
    phone: '9012345678',
    date: '2026-06-18T11:00:00.000Z',
    channel: 'SMS',
    campaign: 'Digital Savings Promotion',
    campaign_id: 'cmp-003',
    duration: '—',
    duration_seconds: 0,
    outcome: 'Declined',
    sentiment: 'Negative',
    status: 'completed',
    agent: 'TARA SMS Agent',
    intent: 'Opt-out',
    summary: 'Customer replied STOP to opt out of SMS outreach.',
    reasoning: 'Consent withdrawn. Lead removed from SMS channel sequences.',
    transcript: [
      { sender: 'agent', text: 'Open a Digital Savings Account today — zero balance, 6.5% interest. Apply: sbi.ly/save' },
      { sender: 'user', text: 'STOP' },
    ],
  },
];

export function getDummyInteractionById(id) {
  return DUMMY_INTERACTION_HISTORY.find(i => i.interaction_id === id);
}

/** Rich detail payloads for Interaction Detail page (keyed by interaction_id). */
export const DUMMY_INTERACTION_DETAILS = {
  'int-001': {
    customer: {
      name: 'Priya Nair',
      customer_id: 'demo-lead-001',
      phone: '9876543210',
      email: 'priya.nair@example.com',
      segment: 'Affluent Metro',
      city: 'Mumbai',
      profile_type: 'External',
      credit_score: 742,
      account_tenure_years: 4,
    },
    campaign_info: {
      name: 'Q3 Personal Loan Drive',
      campaign_id: 'cmp-001',
      product: 'Personal Loan',
      target_audience: 'High-income Metro Users',
      channel: 'Email',
      status: 'Active',
    },
    call_metadata: {
      call_id: 'CA-7f3a9b2e1c',
      session_id: 'sess-int-001-voice',
      direction: 'outbound',
      started_at: '2026-07-14T10:20:46.000Z',
      ended_at: '2026-07-14T10:23:00.000Z',
      duration: '2m 14s',
      duration_seconds: 134,
      channel: 'Voice',
      agent: 'TARA Voice AI',
      status: 'completed',
      recording_available: true,
      language: 'en-IN',
      twilio_sid: 'CA7f3a9b2e1c4d5e6f',
    },
    ai_summary:
      'Priya showed strong purchase intent during a Personal Loan outreach call. She asked specific questions about documentation requirements — a high-confidence buying signal. TARA sent a WhatsApp application link and logged interest for loan specialist follow-up.',
    customer_intent: {
      primary: 'Loan documentation inquiry',
      confidence: 0.91,
      secondary: 'Rate comparison',
      keywords: ['documents', 'EMI', 'application link', 'WhatsApp'],
      intent_category: 'purchase_intent',
    },
    sentiment_analysis: {
      overall: 'Positive',
      score: 0.84,
      trend: 'improving',
      breakdown: [
        { phase: 'Introduction', sentiment: 'Neutral', score: 0.55 },
        { phase: 'Needs Discovery', sentiment: 'Positive', score: 0.72 },
        { phase: 'Product Pitch', sentiment: 'Positive', score: 0.88 },
        { phase: 'Closing', sentiment: 'Positive', score: 0.91 },
      ],
    },
    outcome_detail: {
      label: 'Interested',
      confidence: 0.88,
      conversion_probability: 0.78,
      next_stage: 'Application',
      disposition_code: 'INT-001',
    },
    follow_up: {
      recommendation:
        'Send WhatsApp reminder in 24 hours if application is not started. Escalate to human loan officer if no response within 48 hours.',
      priority: 'High',
      channel: 'WhatsApp',
      scheduled_at: '2026-07-15T10:00:00.000Z',
      action_items: [
        'Confirm WhatsApp link delivery',
        'Schedule loan officer callback if application incomplete by EOD',
        'Update CRM journey stage to "Application Pending"',
      ],
    },
    explainability_notes: [
      {
        code: 1,
        feature: 'consent',
        explanation: 'Customer opted in to voice outreach during prior SMS campaign — consent verified.',
        impact: 'high',
      },
      {
        code: 2,
        feature: 'lead_quality_score',
        explanation: 'Lead quality score 82/100 — above campaign threshold of 65.',
        impact: 'high',
      },
      {
        code: 3,
        feature: 'credit_score',
        explanation: 'Credit score 742 supports pre-approved loan offer up to ₹8.5L.',
        impact: 'medium',
      },
      {
        code: 4,
        feature: 'digital_engagement_score',
        explanation: 'High YONO app usage (18 logins/month) correlates with faster application completion.',
        impact: 'medium',
      },
      {
        code: 5,
        feature: 'previous_campaign_response',
        explanation: 'Responded positively to Q2 savings campaign — cross-sell propensity elevated.',
        impact: 'low',
      },
    ],
  },
  'int-004': {
    customer: {
      name: 'Arjun Das',
      customer_id: 'lead-6',
      phone: '9876543210',
      email: 'arjun.das@example.com',
      segment: 'Gen Z Professional',
      city: 'Bangalore',
      profile_type: 'External',
      credit_score: 698,
      account_tenure_years: 0,
    },
    campaign_info: {
      name: 'Digital Savings Promotion',
      campaign_id: 'cmp-003',
      product: 'Digital Savings Account',
      target_audience: 'Gen Z / Young Professionals',
      channel: 'WhatsApp',
      status: 'Completed',
    },
    call_metadata: {
      call_id: 'WA-4b8c2d1e9f',
      session_id: 'sess-int-004-whatsapp',
      direction: 'outbound',
      started_at: '2026-06-28T11:26:00.000Z',
      ended_at: '2026-06-28T11:30:05.000Z',
      duration: '4m 05s',
      duration_seconds: 245,
      channel: 'WhatsApp',
      agent: 'TARA WhatsApp Agent',
      status: 'completed',
      recording_available: false,
      language: 'en-IN',
    },
    ai_summary:
      'Arjun completed full Digital Savings Account onboarding via WhatsApp-guided video KYC. Account activated same day with virtual debit card issued. Conversion logged — campaign target achieved.',
    customer_intent: {
      primary: 'Account opening',
      confidence: 0.96,
      secondary: 'Product feature inquiry',
      keywords: ['KYC', 'video', 'debit card', 'YONO'],
      intent_category: 'conversion',
    },
    sentiment_analysis: {
      overall: 'Positive',
      score: 0.92,
      trend: 'stable',
      breakdown: [
        { phase: 'Greeting', sentiment: 'Positive', score: 0.80 },
        { phase: 'KYC Guidance', sentiment: 'Positive', score: 0.90 },
        { phase: 'Account Activation', sentiment: 'Positive', score: 0.95 },
      ],
    },
    outcome_detail: {
      label: 'Converted',
      confidence: 0.97,
      conversion_probability: 1.0,
      next_stage: 'Onboarding Complete',
      disposition_code: 'CNV-001',
    },
    follow_up: {
      recommendation:
        'Send welcome kit via email. Trigger cross-sell for Recurring Deposit after 7 days of account activity.',
      priority: 'Low',
      channel: 'Email',
      scheduled_at: '2026-07-05T09:00:00.000Z',
      action_items: [
        'Send YONO app onboarding tips',
        'Schedule RD cross-sell after 7-day activation window',
      ],
    },
    explainability_notes: [
      {
        code: 1,
        feature: 'communication_readiness',
        explanation: 'WhatsApp channel preferred — 94% message open rate for this segment.',
        impact: 'high',
      },
      {
        code: 2,
        feature: 'digital_engagement_score',
        explanation: 'Gen Z segment with high mobile-first behaviour — WhatsApp flow optimal.',
        impact: 'high',
      },
      {
        code: 3,
        feature: 'lead_quality_score',
        explanation: 'Lead score 77 — qualified for instant digital onboarding path.',
        impact: 'medium',
      },
    ],
  },
  'int-013': {
    customer: {
      name: 'Rohan Gupta',
      customer_id: 'lead-8',
      phone: '9012345678',
      email: 'rohan.g@example.com',
      segment: 'Mass Market',
      city: 'Pune',
      profile_type: 'External',
      credit_score: 612,
      account_tenure_years: 1,
    },
    campaign_info: {
      name: 'Digital Savings Promotion',
      campaign_id: 'cmp-003',
      product: 'Digital Savings Account',
      target_audience: 'Gen Z / Young Professionals',
      channel: 'WhatsApp',
      status: 'Completed',
    },
    call_metadata: {
      call_id: 'SMS-opt-out-013',
      session_id: 'sess-int-013-sms',
      direction: 'outbound',
      started_at: '2026-06-18T11:00:00.000Z',
      ended_at: '2026-06-18T11:00:12.000Z',
      duration: '—',
      duration_seconds: 12,
      channel: 'SMS',
      agent: 'TARA SMS Agent',
      status: 'completed',
      recording_available: false,
      language: 'en-IN',
    },
    ai_summary:
      'Customer replied STOP to opt out of SMS outreach. Consent withdrawn and lead removed from all SMS sequences. No further SMS contact permitted per TRAI regulations.',
    customer_intent: {
      primary: 'Opt-out',
      confidence: 0.99,
      secondary: null,
      keywords: ['STOP', 'unsubscribe'],
      intent_category: 'opt_out',
    },
    sentiment_analysis: {
      overall: 'Negative',
      score: 0.22,
      trend: 'declining',
      breakdown: [
        { phase: 'SMS Delivery', sentiment: 'Neutral', score: 0.50 },
        { phase: 'Customer Reply', sentiment: 'Negative', score: 0.15 },
      ],
    },
    outcome_detail: {
      label: 'Declined',
      confidence: 0.99,
      conversion_probability: 0.0,
      next_stage: 'Suppressed',
      disposition_code: 'OPT-001',
    },
    follow_up: {
      recommendation:
        'Remove from SMS channel permanently. Re-engage only via email if consent re-obtained through YONO preference centre.',
      priority: 'None',
      channel: 'None',
      scheduled_at: null,
      action_items: [
        'Flag lead as SMS-suppressed in CRM',
        'Audit consent registry',
        'Exclude from future SMS campaigns',
      ],
    },
    explainability_notes: [
      {
        code: 1,
        feature: 'consent',
        explanation: 'Explicit STOP reply — SMS consent revoked per regulatory requirement.',
        impact: 'high',
      },
      {
        code: 2,
        feature: 'previous_campaign_response',
        explanation: 'Prior email campaign had no engagement — low propensity segment.',
        impact: 'medium',
      },
    ],
  },
};

function sentimentToScore(label) {
  const map = {
    Positive: 0.85,
    'Neutral-Positive': 0.65,
    Neutral: 0.50,
    Negative: 0.20,
  };
  return map[label] ?? 0.50;
}

function buildDefaultInteractionDetail(base) {
  const campaign = DUMMY_CAMPAIGNS.find(c => c.campaign_id === base.campaign_id);
  const score = sentimentToScore(base.sentiment);
  const isConverted = base.outcome === 'Converted';
  const isDeclined = base.outcome === 'Declined' || base.outcome === 'No Response';

  return {
    customer: {
      name: base.customer_name,
      customer_id: base.customer_id || '—',
      phone: base.phone || '—',
      email: base.email || '—',
      segment: 'Retail Banking',
      city: '—',
      profile_type: 'External',
      credit_score: null,
      account_tenure_years: null,
    },
    campaign_info: {
      name: base.campaign,
      campaign_id: base.campaign_id,
      product: campaign?.product || '—',
      target_audience: campaign?.target_audience || '—',
      channel: campaign?.channel || base.channel,
      status: campaign?.status || '—',
    },
    call_metadata: {
      call_id: `CA-${base.interaction_id}`,
      session_id: `sess-${base.interaction_id}`,
      direction: 'outbound',
      started_at: base.date,
      ended_at: base.date,
      duration: base.duration || '—',
      duration_seconds: base.duration_seconds || 0,
      channel: base.channel,
      agent: base.agent || 'TARA Agent',
      status: base.status || 'completed',
      recording_available: base.channel === 'Voice',
      language: 'en-IN',
    },
    ai_summary: base.summary || 'Interaction completed. No additional summary available.',
    customer_intent: {
      primary: base.intent || 'General inquiry',
      confidence: 0.75,
      secondary: null,
      keywords: [],
      intent_category: 'general',
    },
    sentiment_analysis: {
      overall: base.sentiment || 'Neutral',
      score,
      trend: 'stable',
      breakdown: [
        { phase: 'Session', sentiment: base.sentiment || 'Neutral', score },
      ],
    },
    outcome_detail: {
      label: base.outcome,
      confidence: isConverted ? 0.95 : isDeclined ? 0.85 : 0.72,
      conversion_probability: isConverted ? 1.0 : isDeclined ? 0.1 : 0.55,
      next_stage: isConverted ? 'Onboarding' : isDeclined ? 'Suppressed' : 'Nurture',
      disposition_code: 'GEN-001',
    },
    follow_up: {
      recommendation: base.reasoning || 'Review interaction and schedule appropriate follow-up.',
      priority: isConverted ? 'Low' : isDeclined ? 'None' : 'Medium',
      channel: base.channel === 'Voice' ? 'WhatsApp' : base.channel,
      scheduled_at: null,
      action_items: ['Review session notes', 'Update CRM journey stage'],
    },
    explainability_notes: [
      {
        code: 1,
        feature: 'lead_quality_score',
        explanation: 'Lead qualified for campaign based on ML conversion model score.',
        impact: 'medium',
      },
      {
        code: 2,
        feature: 'communication_readiness',
        explanation: `${base.channel} channel selected based on customer channel preference.`,
        impact: 'medium',
      },
    ],
  };
}

/** Merge a base interaction record with rich detail JSON for the detail page. */
export function getInteractionDetail(base) {
  if (!base) return null;
  const overlay = DUMMY_INTERACTION_DETAILS[base.interaction_id];
  const defaults = buildDefaultInteractionDetail(base);
  if (!overlay) return { ...base, ...defaults };

  return {
    ...base,
    ...defaults,
    ...overlay,
    customer: { ...defaults.customer, ...overlay.customer },
    campaign_info: { ...defaults.campaign_info, ...overlay.campaign_info },
    call_metadata: { ...defaults.call_metadata, ...overlay.call_metadata },
    customer_intent: { ...defaults.customer_intent, ...overlay.customer_intent },
    sentiment_analysis: { ...defaults.sentiment_analysis, ...overlay.sentiment_analysis },
    outcome_detail: { ...defaults.outcome_detail, ...overlay.outcome_detail },
    follow_up: { ...defaults.follow_up, ...overlay.follow_up },
    explainability_notes: overlay.explainability_notes || defaults.explainability_notes,
    transcript: overlay.transcript || base.transcript || [],
  };
}