"""Prompt construction for Explainable AI explanations."""

from __future__ import annotations

import json
from typing import Any

SYSTEM_PROMPT = """You are an Explainable AI assistant for a banking decision-support platform.

You do not make lending decisions.
You only explain the existing ML predictions provided in the user message.

Rules:
- Use professional banking language suitable for relationship managers and audit reports.
- Do not invent facts, scores, or products not present in the supplied data.
- Do not change recommendations or suggest alternative products.
- Do not override repayment capacity, product selection, conversion probability, or priority levels.
- Explain why the ML models reached their conclusions using only the supplied structured data and reason codes.
- Return valid JSON only with exactly these keys:
  summary, repayment_explanation, product_explanation, conversion_explanation,
  confidence_summary, reason_codes

The reason_codes in your response must be a subset of or match the supplied top_reason_codes — do not add new reason codes."""


class PromptBuilder:
    """Builds system and user prompts for Azure OpenAI explanation generation."""

    def build_messages(self, decision_summary: dict[str, Any]) -> list[dict[str, str]]:
        user_payload = {
            "instruction": (
                "Explain the following ML decision summary for a banking audience. "
                "All predictions are final — your role is explanation only."
            ),
            "decision_summary": decision_summary,
        }
        return [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps(user_payload, indent=2, default=str)},
        ]

    def build_fallback(self, decision_summary: dict[str, Any]) -> dict[str, Any]:
        """Deterministic template explanation when LLM is unavailable."""
        name = decision_summary.get("customer_name", "The customer")
        repayment = decision_summary.get("repayment_capacity", "N/A")
        product = decision_summary.get("recommended_product", "N/A")
        conversion = decision_summary.get("conversion_probability")
        reasons = decision_summary.get("top_reason_codes", [])

        conversion_text = (
            f"The lead conversion model predicts a {conversion}% probability of conversion after outreach."
            if conversion is not None
            else "Lead conversion prediction is not available for this profile type."
        )

        confidence = "High"
        if repayment in ("Low", "Medium"):
            confidence = "Medium"
        if repayment == "Low":
            confidence = "Low"

        return {
            "summary": (
                f"{name} demonstrates financial profile characteristics consistent with "
                f"{repayment} repayment capacity as determined by the ML models."
            ),
            "repayment_explanation": (
                f"The repayment model predicts {repayment} repayment capacity "
                f"with {decision_summary.get('repayment_confidence', 'N/A')}% confidence, "
                f"based on income, EMI burden, savings behaviour, credit score, and financial health indicators."
            ),
            "product_explanation": (
                f"{product} is the top ML-recommended product based on eligibility rules and ranking "
                f"against the customer's profile and repayment capacity. "
                f"This recommendation is generated by the product recommendation engine — not by this explanation layer."
            ),
            "conversion_explanation": conversion_text,
            "confidence_summary": f"Overall confidence in the ML outputs is {confidence}.",
            "reason_codes": reasons,
        }
